### ISSUE TITLE
Create Bicep File for Front-end App

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/gccollab-frontend#10]

**Comment by Phanoix** [comment]
for reference: https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-bicep
and the gccollab PR instance bicep, while having a lot of extra parts that aren't relevant here, should be a useful example.

**Comment by doug0102** [comment]
Closed by [Pull Request #134](https://github.com/gctools-outilsgc/gccollab-frontend/pull/134)
