### ISSUE TITLE
Include all e2e tests in workflow

### ISSUE THREAD

**Issue by vid** [gctools-outilsgc/gccollab-frontend#205]
Adi created a number of component-focused tests, include them all in the workflow.

**Comment by vid** [comment]
This needs gh-pages to be set up for this repo. That site can then be used for documentation and reviews.
![image](https://github.com/gctools-outilsgc/gccollab-frontend/assets/68174/13badc3b-643a-4b84-84af-e4b2dd89bf32)

**Comment by vid** [comment]
@doug0102  can you enable this?

**Comment by doug0102** [comment]
> @doug0102 can you enable this?

Sure I can look into it. Do you just need a live site to run the e2e tests on? If so there's the [this one](https://gccollab-dev.azurewebsites.net/) that always has the main branch code. There are also other environments that get created during a pull request you could run the e2e tests on.

**Comment by vid** [comment]
It doesn't need a live site, at least not for now. It will use [this script](https://github.com/withhaibun/haibun-e2e-tests/blob/main/.github/workflows/test.yml) which will install and run the front end server, test against it, and then check out the github pages branch, commit the results into that page, and then create a review using github pages, which can be a link off the main gccollab-frontend github pages site. See the link "here" [here](https://github.com/withhaibun/haibun-e2e-tests?tab=readme-ov-file#haibun-e2e-tests) for an example.

So all this needs is to enable a github pages site at a branch, eg gh-pages, and a link to the reviews folder from the readme (or whatever ends up being the 'front page' of the repo's github pages.

**Comment by vid** [comment]
OK one more thing, we need to use a developer PAT (personal access token) to push to the gh-pages branch from the github action. Attached is what it looks like in withhaibun.

![image](https://github.com/gctools-outilsgc/gccollab-frontend/assets/68174/52a8ec1e-6d01-4e4c-a418-da2ea8829d1f)

**Comment by doug0102** [comment]
I believe I'm already doing that in some of my workflows in the project. Like in [this workflow](https://github.com/gctools-outilsgc/gccollab-frontend/blob/main/.github/workflows/dependency-graph.yml) where I update the dependency graph. Is this what you mean?

**Comment by vid** [comment]
Oh, it might already be enabled then, I don't have access to check.

**Comment by vid** [comment]
Yay. https://gctools-outilsgc.github.io/gccollab-frontend/#:~:text=npm%20run%20test-,E2E%20test%20reviews,-are%20available%20here @AdiMakkar 
Though the badge should be red, since some tests failed. Will make a PR after that.
