### ISSUE TITLE
Update the footer with the new design

### ISSUE THREAD

**Issue by doug0102** [gctools-outilsgc/gccollab-frontend#32]
### Description
The footer needs to be updated to match the new design outlined [here](https://www.figma.com/file/mbJusS7ADxfO7s8lkNLc9B/GCColab-HIFI?node-id=1099-4779&t=9A3MIcFdfUPAx0H5-0). The component already exists in the project so some tweaks to the template and styles is all that's required.

### Requirements
- Update the footer to match what's shown in the design.

### Acceptance Criteria
- Footer component renders.
- It sticks to the bottom of the page.
- The hyperlinks work and make use of `RouterLink`
- It matches the design document.
- Fully accessible and translated.
- Has at least 1 passing unit test.

**Comment by AdiMakkar** [comment]
check #56

**Comment by AdiMakkar** [comment]
Closing #56. Will reopen if required.
